### ISSUE TITLE
Add flag to Tackle CR to change the require password setting

### ISSUE THREAD

**Issue by wkulhanek** [konveyor/tackle2-operator#101]
Currently when setting up a new Tackle 2 instance via the Operator the Keycloak configuration requires a change of password on the first login. This prevents automatic seeding of Tackle for demo / lab / workshop environments - unless authentication is turned off. Which is not desirable.

Add a flag to the Tackle CR to optionally turn off the requirement to change the password. Which would change the configuration config map (https://github.com/konveyor/tackle2-operator/blob/main/roles/tackle/templates/configmap-keycloak-sso.yml.j2) - guessing around line 530.

Also potentially add a field to the Tackle CR to specify a password. Again this could be generated during automatic deployment and would not be less secure than the current default 'password'. 

@rromannissen @aufi FYI

**Comment by fbladilo** [comment]
This has been addressed by #105 , closing.
