### ISSUE TITLE
Enable use of pinned image checksums in releases opposed to floating tags

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/tackle2-operator#144]
We have some users who are running on 'disconnected' or 'airgapped' OpenShift clusters that want to consume Konveyor releases yet are blocked from our use of floating tags opposed to pinned image checksums.  

The ask is to update our release process so when we create new upstream Konveyor releases we pin to specific image checksums.

For background info https://www.redhat.com/en/blog/using-red-hat-openshift-operatorhub-restricted-networks

**Comment by djzager** [comment]
This seems a better fit for this issue as the most meaningful place to put image checksums is in the CSVs we publish to community-operators.

**Comment by shawn-hurley** [comment]
I am a big +1 on SHA references because we know exactly what is being used then regarding user environments.

**Comment by fbladilo** [comment]
@djzager It would also be nice to inject an image label with the commit hash for each component image built , i.e :
```
LABEL  io.openshift.build.commit.id="${CI_TACKLE2_HUB_UPSTREAM_COMMIT}"
```

**Comment by djzager** [comment]
@jmontleon I think your PR #161 fixes this. Is that right?

**Comment by jmontleon** [comment]
Yes. This is the PR created by the workflow test run:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2432/files#diff-da872ac04b3de675cf90eda44f62823cb1bd18f828d0aed49d551a5d4ec830d5R147-R162
