### ISSUE TITLE
Publish operator to community-operators for non OKD/OCP clusters

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/tackle2-operator#150]
My understanding is that we are currently publishing to operatorhub for consumption by OKD/OCP clusters via:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/tackle-operator

We have not yet published a newer "tackle v2" to the more generic k8s operatorhub catalog:
https://github.com/operator-framework/community-operators/tree/master/community-operators

Raising this issue so we can consider if we should publish to the more generic catalog in addition to the OKD/OCP specific.

**Comment by fbladilo** [comment]
@jwmatthews We are publishing to both , I believe that repository is obsolete , check here : 

https://github.com/k8s-operatorhub/community-operators/tree/main/operators/tackle-operator

This is our operator in k8s : 

 https://operatorhub.io/operator/tackle-operator
