### ISSUE TITLE
Add route to the hub API.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-operator#28]
Add route to the hub API: hub-konveyor-tackle.apps.cluster-jortel.v2v.bos.redhat.com with TLS.

We may want to rename the UI route to reduce the number of "tackle" in it and be more specific.
Suggest:  ui-konveyor-tackle

I'm not sure what the convention is but assume it is to include "konveyor" and "tackle" in it somewhere.

**Comment by fbladilo** [comment]
@jortel The only route we deploy currently is the UI route , the name is tackle and it is derived from app_name in operator. Now that we will need an additional route perhaps it makes sense to either call them: 

tackle-ui and tackle-hub or perhaps tackle (for UI main route) and tackle-hub (for hub)

As a secondary point, do we need this hub route also available in kubernetes? k8s does not support routes so it will have to be an Ingress.

**Comment by jortel** [comment]
I'm not sure what the naming answer is but including the name "tackle" more than once seems odd (and like we don't know what we're doing), IMHO.

As for route vs ingress, I understand and was using the term _generally_ expecting that you would create an ingress for k8s.

**Comment by fbladilo** [comment]
Closing this one as it is not needed at the time
