### ISSUE TITLE
Hub SA security context.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-operator#76]
Update tackle-hub SA like:
```
oc adm policy add-scc-to-user anyuid -z tackle-hub
```
Probably need explict namespace instead of `-z`.

Needed so hub can run task pods with explicit security context to:
```
runAsUser: 0 (actual root)
```
This is needed so addon SSH component can create `/etc/ssh/known_hosts`  Also, make troubleshooting MUCH easier when ssh(ing) to the pod.  The injected (generated) user on OCP is a pain.

This is mainly need for OCP.

**Comment by fbladilo** [comment]
@jortel Let's discuss this one , an ssh client or library can be instructed via options to redirect known_hosts to /dev/null , typical use for this cases : `ssh -o "UserKnownHostsFile=/dev/null"`
