### ISSUE TITLE
error: unable to recognize "STDIN": no matches for kind "Tackle" in version "tackle.io/v1alpha1"

### ISSUE THREAD

**Issue by rccclr** [konveyor/tackle2-operator#77]
Hello
Error in steps for process installation.
Many thanks

```
$ kubectl create -f https://operatorhub.io/install/tackle-operator.yaml
namespace/my-tackle-operator created
operatorgroup.operators.coreos.com/operatorgroup created
subscription.operators.coreos.com/my-tackle-operator created
```
```
$ curl https://raw.githubusercontent.com/konveyor/tackle-operator/main/src/main/resources/k8s/tackle/tackle.yaml | kubectl apply -n my-tackle-operator -f -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   696  100   696    0     0   2676      0 --:--:-- --:--:-- --:--:--  2676
error: unable to recognize "STDIN": no matches for kind "Tackle" in version "tackle.io/v1alpha1"
```

![image](https://user-images.githubusercontent.com/5550864/169764876-8c2bcc18-d6c3-4886-9b5b-32d23305f78c.png)

**Comment by fbladilo** [comment]
@rccclr I believe you are installing Tackle2 beta but attempting to create the Tackle CR from stable/v1.x , please use the following Tackle CR if you want to use Tackle2 beta (it has changed) : 
```
$ cat << EOF | kubectl apply -f -
kind: Tackle
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: tackle
  namespace: konveyor-tackle
spec:
EOF
```
More info here : 

https://github.com/konveyor/tackle2-operator#creating-a-tackle-cr

**Comment by rccclr** [comment]
Many thanks @fbladilo with your change, the result is ok, no error, with version "Tackle2 beta".

With this version Tackle2, I have not found the URL to access the UI console (in the manual it indicates that in Services-Ingresses a "tacke-sample" appears with Endpoint, but it is not).

I would like to try the Tackle product, I don't care, which version. 

I'm following the instructions here: https://tackle-docs.konveyor.io/documentation/doc-installing-and-using-tackle/master/index.html

```
kubectl create -f https://operatorhub.io/install/tackle-operator.yaml
kubectl get all -n my-tackle-operator
kubectl apply -n my-tackle-operator -f https://raw.githubusercontent.com/konveyor/tackle-operator/main/src/main/resources/k8s/tackle/tackle.yaml
```
But the error is:
```
$ kubectl apply -n my-tackle-operator -f https://raw.githubusercontent.com/konveyor/tackle-operator/main/src/main/resources/k8s/tackle/tackle.yaml
error: unable to recognize "https://raw.githubusercontent.com/konveyor/tackle-operator/main/src/main/resources/k8s/tackle/tackle.yaml": no matches for kind "Tackle" in version "tackle.io/v1alpha1"
```

If you know other documentation to install it, I would appreciate it.

Many thanks

**Comment by fbladilo** [comment]
@rccclr We are out of beta and now have the 2.0 documentation available : https://konveyor.github.io/tackle/ , please let us know , it is our first revision of the docs and we surely welcome feedback.

**Comment by fbladilo** [comment]
This one seems stale but please feel free to re-open otherwise....
