### ISSUE TITLE
Rename PATHFINDER_API_URL env variable for tackle2-ui

### ISSUE THREAD

**Issue by gildub** [konveyor/tackle2-operator#8]
On tackle2-ui, the current environment variable for pathfinder service is:
PATHFINDER_API_URL = http://tackle-pathfinder-api:8080

This might very opinionated (as naming could be) but not having "api" in the name of the pathfinder service would make it on par with TACKLE_HUB. The services are API anyway.
 
So we could change not only the env variable but also the service name itself so we could have:
PATHFINDER_URL = http://tackle-pathfinder:8080

**Comment by fbladilo** [comment]
Resolved via #10
